<?php
/**
 * settings.ini.php
 * 
 * Defines initialization settings for the application.
 * DO NOT edit this file, to override these settings use settings.local.ini.php instead.
 * Any changes in the local ini file will override the settings found here.
 */

global $SETTINGS;

// tagged version
$SETTINGS['general']['application_name'] = 'my_application';
$SETTINGS['general']['version'] = '1.0.0';

// always leave as false when running as production server
$SETTINGS['general']['development_mode'] = false;

// the location of application's internal path
$SETTINGS['path']['APPLICATION'] = '/usr/local/lib/my_application';
