DELIMITER $$
    
DROP TRIGGER IF EXISTS hold_AFTER_INSERT $$
CREATE DEFINER = CURRENT_USER TRIGGER hold_AFTER_INSERT AFTER INSERT ON hold FOR EACH ROW
BEGIN
  CALL remove_duplicate_holds( NEW.participant_id );
  CALL update_participant_last_hold( NEW.participant_id );
END$$

DROP TRIGGER IF EXISTS hold_AFTER_UPDATE $$
CREATE DEFINER = CURRENT_USER TRIGGER hold_AFTER_UPDATE AFTER UPDATE ON hold FOR EACH ROW
BEGIN
  CALL update_participant_last_hold( NEW.participant_id );
END$$

DROP TRIGGER IF EXISTS hold_AFTER_DELETE $$
CREATE DEFINER = CURRENT_USER TRIGGER hold_AFTER_DELETE AFTER DELETE ON hold FOR EACH ROW
BEGIN
  CALL update_participant_last_hold( OLD.participant_id );
END$$

DELIMITER ;
