#!/usr/bin/php
<?php
/** 
 * Utility which prints the version tag value
 * @author Patrick Emond <emondpd@mcmaster.ca>
 */

// validate arguments
if( 1 != $argc )
{
  print "Script expects exactly zero arguments.\n";
  exit( 1 );
}

print preg_replace( '/^.+ = \'(.*)\';$/',
                    '\\1',
                    exec( 'grep cenozo_version app/settings.ini.php' ) )."\n";
