#!/usr/bin/php
<?php
/** 
 * Utility which prints the version tag value
 * @author Patrick Emond <emondpd@mcmaster.ca>
 */

$filename = 'app/settings.ini.php';

// validate arguments
if( 1 != $argc )
{
  print "Script expects exactly zero arguments.\n";
  exit( 1 );
}

// make sure ini file exists (checking ./ and ../)
if( !file_exists( $filename ) ) $filename = '../'.$filename;

if( !file_exists( $filename ) )
{
  print "Cannot find ini file.\n";
  exit( 3 );
}

// replace the general-version setting in the main ini file
$app_settings = array();
include $filename;

if( !isset( $fwk_settings ) ||
    !is_array( $fwk_settings ) ||
    !array_key_exists( 'general', $fwk_settings ) ||
    !is_array( $fwk_settings['general'] ) ||
    !array_key_exists( 'cenozo_version', $fwk_settings['general'] ) )
{
  print "Cannot find version information.\n";
  exit( 4 );
}

print $fwk_settings['general']['cenozo_version']."\n";
?>
