#!/bin/sh
# 
# build_docs
# 
# Builds API documentation for Cenozo using phpDocumentor.
# @author Patrick Emond <emondpd@mcmaster.ca>

if [ ! -d "phpdoc" ]; then
  # create phpdoc/ if id doesn't already exist
  mkdir phpdoc
else
  # clean out phpdoc/ of old files
  rm -rf phpdoc/*
fi

# generate the documentation
phpdoc -o "HTML:frames:earthli" -ti "Cenozo API Documentation" -d ../api/ -t phpdoc/
