CREATE TABLE site (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  update_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  create_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  name VARCHAR(45) NOT NULL,
  timezone VARCHAR(45) NOT NULL DEFAULT 'Canada/Eastern',
  title VARCHAR(45) NULL DEFAULT NULL,
  phone_number VARCHAR(45) NULL DEFAULT NULL,
  address1 VARCHAR(512) NULL DEFAULT NULL,
  address2 VARCHAR(512) NULL DEFAULT NULL,
  city VARCHAR(100) NULL DEFAULT NULL,
  region_id INT(10) UNSIGNED NULL DEFAULT NULL,
  postcode VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX uq_name (name ASC),
  INDEX fk_site_region_id (region_id ASC),
  CONSTRAINT fk_site_region_id
    FOREIGN KEY (region_id)
    REFERENCES region (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;
