<?php
/**
 * cenozo.ini.php
 * 
 * Defines initialization settings for cenozo.
 * DO NOT edit this file, to override these settings use cenozo.local.ini.php instead.  Any
 * changes in the local ini file will override the settings found here.
 * 
 * @author Patrick Emond <emondpd@mcmaster.ca>
 * @package cenozo
 */

namespace cenozo;
global $SETTINGS;

// tagged version
$SETTINGS[ 'general' ][ 'version' ] = '0.1.0';

// always leave as false when running as production server
$SETTINGS[ 'general' ][ 'development_mode' ] = false;

// determine the operation type from the script name
$script = $_SERVER['SCRIPT_NAME'];
if( false !== strpos( $script, 'slot/index.php' ) )
{
  $base_url = substr( $_SERVER['SCRIPT_NAME'], 0, -15 );
  $SETTINGS[ 'general' ][ 'operation_type' ] = 'widget';
}
else if( false !== strpos( $script, 'pull.php' ) )
{
  $base_url = substr( $_SERVER['SCRIPT_NAME'], 0, -9 );
  $SETTINGS[ 'general' ][ 'operation_type' ] = 'pull';
}
else if( false !== strpos( $script, 'push.php' ) )
{
  $base_url = substr( $_SERVER['SCRIPT_NAME'], 0, -9 );
  $SETTINGS[ 'general' ][ 'operation_type' ] = 'push';
}
else
{
  $base_url = substr( $_SERVER['SCRIPT_NAME'], 0, -10 );
  $SETTINGS[ 'general' ][ 'operation_type' ] = 'index';
}

$SETTINGS[ 'url' ][ 'CENOZO' ] = 'http'.
                                     ( 'on' == $_SERVER["HTTPS"] ? 's' : '' ).
                                     '://'.$_SERVER["HTTP_HOST"].$base_url;
$SETTINGS[ 'path' ][ 'COOKIE' ] = $base_url.'/';
unset( $script );
unset( $base_url );

// the location of cenozo internal path
$SETTINGS[ 'path' ][ 'CENOZO' ] = '/usr/local/lib/cenozo';

// the location of libraries
$SETTINGS[ 'path' ][ 'ADODB' ] = '/usr/local/lib/adodb';
$SETTINGS[ 'path' ][ 'JS' ] = 'js';
$SETTINGS[ 'path' ][ 'CSS' ] = 'css';

// javascript libraries
$SETTINGS[ 'version' ][ 'JQUERY' ] = '1.4.4';
$SETTINGS[ 'version' ][ 'JQUERY_UI' ] = '1.8.9';

$SETTINGS[ 'url' ][ 'JQUERY' ] = '/jquery';
$SETTINGS[ 'url' ][ 'JQUERY_UI' ] = $SETTINGS[ 'url' ][ 'JQUERY' ].'/ui';
$SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ] = $SETTINGS[ 'url' ][ 'JQUERY' ].'/plugins';
$SETTINGS[ 'path' ][ 'JQUERY_UI_THEMES' ] = '/var/www/jquery/ui/css';

$SETTINGS[ 'url' ][ 'JQUERY_JS' ] = 
  $SETTINGS[ 'url' ][ 'JQUERY' ].'/jquery-'.$SETTINGS[ 'version' ][ 'JQUERY' ].'.min.js';
$SETTINGS[ 'url' ][ 'JQUERY_UI_JS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_UI' ].'/js/jquery-ui-'.$SETTINGS[ 'version' ][ 'JQUERY_UI' ].'.custom.min.js';

$SETTINGS[ 'url' ][ 'JQUERY_LAYOUT_JS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ].'/layout.js';
$SETTINGS[ 'url' ][ 'JQUERY_COOKIE_JS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ].'/cookie.js';
$SETTINGS[ 'url' ][ 'JQUERY_HOVERINTENT_JS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ].'/hoverIntent.js';
$SETTINGS[ 'url' ][ 'JQUERY_METADATA_JS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ].'/metadata.js';
$SETTINGS[ 'url' ][ 'JQUERY_FLIPTEXT_JS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ].'/flipText.js';
$SETTINGS[ 'url' ][ 'JQUERY_EXTRUDER_JS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ].'/extruder.js';
$SETTINGS[ 'url' ][ 'JQUERY_LOADING_JS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ].'/loading.js';
$SETTINGS[ 'url' ][ 'JQUERY_LOADING_OVERFLOW_JS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ].'/loading.overflow.js';
$SETTINGS[ 'url' ][ 'JQUERY_JEDITABLE_JS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ].'/jeditable.js';
$SETTINGS[ 'url' ][ 'JQUERY_TIMEPICKER_JS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ].'/timepicker.js';
$SETTINGS[ 'url' ][ 'JQUERY_RIGHTCLICK_JS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ].'/rightClick.js';
$SETTINGS[ 'url' ][ 'JQUERY_TOOLTIP_JS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ].'/tooltip.js';
$SETTINGS[ 'url' ][ 'JQUERY_FULLCALENDAR_JS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ].'/fullcalendar.js';
$SETTINGS[ 'url' ][ 'JQUERY_FONTSCALE_JS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ].'/fontscale.js';
$SETTINGS[ 'url' ][ 'JQUERY_TIMERS_JS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ].'/timers.js';

// css files
$SETTINGS[ 'url' ][ 'JQUERY_UI_THEMES' ] = $SETTINGS[ 'url' ][ 'JQUERY_UI' ].'/css';
$SETTINGS[ 'url' ][ 'JQUERY_FULLCALENDAR_CSS' ] =
  $SETTINGS[ 'url' ][ 'JQUERY_PLUGINS' ].'/fullcalendar.css';

// the location of log files
$SETTINGS[ 'path' ][ 'LOG_FILE' ] = '/var/local/cenozo/log';

// the location of the compiled template cache
$SETTINGS[ 'path' ][ 'TEMPLATE_CACHE' ] =
  '/tmp/cenozo/'.substr( str_replace( '/', '_', dirname( __FILE__ ) ), 1 );

// database settings
$SETTINGS[ 'db' ][ 'driver' ] = 'mysql';
$SETTINGS[ 'db' ][ 'server' ] = 'localhost';
$SETTINGS[ 'db' ][ 'username' ] = 'cenozo';
$SETTINGS[ 'db' ][ 'password' ] = '';
$SETTINGS[ 'db' ][ 'database' ] = 'cenozo';
$SETTINGS[ 'db' ][ 'prefix' ] = '';

// ldap settings
$SETTINGS[ 'ldap' ][ 'server' ] = 'localhost';
$SETTINGS[ 'ldap' ][ 'port' ] = 389;
$SETTINGS[ 'ldap' ][ 'base' ] = '';
$SETTINGS[ 'ldap' ][ 'username' ] = '';
$SETTINGS[ 'ldap' ][ 'password' ] = '';
$SETTINGS[ 'ldap' ][ 'active_directory' ] = true;

// themes
$SETTINGS[ 'interface' ][ 'default_theme' ] = 'smoothness';
?>
